### ISSUE TITLE
Build variables not available in Pre and Post-Build events

### ISSUE THREAD

**Issue by FireGiantHelp** [firegiant/HeatWaveSupport#6]
### HeatWave Version

0.9.0.5

### Visual Studio Version

17.3.6

### Repro Steps

Build variables not available in Pre and Post-Build events

1. Create a new blank V3 project
2. Add a post-build event:
    `echo Test $(TargetPath)
3. Build and test that it outputs the path of the .msi file in the build log
4. Convert the project to V4 using Heatwave
5. Build and check the build log. 

See also: https://github.com/wixtoolset/issues/issues/7020

### Actual Result

It only outputs `"Test "` now

### Expected Result

I expect the same output as in V3. None of the build variables seems to be available
This simple example gets converted to a V4 SDK-style project. I don't know how to fix this for SDK projects, but for my real project this was fixed by moving the line up above the tag

**Comment by FireGiantHelp** [comment]
We can reproduce this internally. This issue is on our backlog to fix. We expect this to be fixed in the next preview release.

**Comment by FireGiantHelp** [comment]
This should be fixed in HeatWave v0.9.2. Imports should now be organized to support pre-build and post-build events during conversion.

**Comment by jcrawfor74** [comment]
Hi @FireGiantHelp, 
I am using VS 2022 v17.5.5, with HeatWave extension v1.0.1.1, and this bug still appears to be occurring.

I am attempting to create a bundle so I wish to reference the created .msi files from a simpler relative path that takes into account the differences when building an X86 vs X64 packages. 
(Note: I am 6 hours into using Wix so maybe there is a simpler way :-) )

On the .msi project I have the following post build script with the idea of copying the created .msi file to a published folder, that I can then reference statically and more easily inside the bundle.

`copy $(TargetPath) $(SolutionDir)Published`

When this runs I get the folllowing error
`Error	MSB3073	The command "copy  d:\code\repo\my-application\installation\published" exited with code 1.`

So the `$(SolutionDir)` variable, is working but the `$(TargetPath)` is not.

Other variables that I have also confirmed are NOT working include (but not limited too).

1. $(OutDir)
1. $(PlatformName)
1. $(TargetFileName)

I think you may need to revisit this issue. 
P.S. If you can point me in the direction of where this code re-sides, maybe I can have a crack at fixing. 
P.P.S BTW 6 hours in and I have managed to create .msi installers that copy my config and deployment files, add registry keys, install windows services.. its going pretty well so far.. Simpler documentation for newbies would  be beneficial, otherwise great work.

**Comment by jcrawfor74** [comment]
Note also.. 
Turns out I didn't need most of that as the root path that the command is executed from is the Debug or Release folder e.g.
`bin\x64\Debug` or `bin\x86\Debug` 

So knowing this, I only needed to change my command as follows..

`xcopy ".\en-US\MyApp.msi" $(SolutionDir)Published\ /s/y`

Doesn't change the issue from above but it is a workaround

**Comment by damsad** [comment]
I can confirm @jcrawfor74 behavior reported on 11th May.
HeatWave 1.0.1 and Visual Studio 2022 17.6.3. 
It's impossible to get a response from the macros like $(TargetPath) and the others.
But some like $(Configuration) are working well.
