### ISSUE TITLE
MSB4057 The target "CollectSuggestedVisualStudioComponentIds" does not exist in the project.

### ISSUE THREAD

**Issue by YuliiaKovalova** [firegiant/HeatWaveSupport#73]
### HeatWave Version

1.0.4.5

### Visual Studio Version

17.13.0 Preview 2.0

### Repro Steps

Repo: https://github.com/team-charls/netpbm-wic-codec
- git clone https://github.com/team-charls/netpbm-wic-codec
- Open a Visual Studio 2022 17.13 Preview 2.0 Developer prompt
- cd netpbm-wc-codec
- execute msbuild -t:build -p:Configuration=Release -p:Platform=x64

### Actual Result

Exception during design-time build: MSB4057 The target "CollectSuggestedVisualStudioComponentIds" does not exist in the project.

### Expected Result

Quick fix:
`FireGiant.HeatWave.DesignTime.targets`
contains empty target :
` <Target Name="CollectSuggestedVisualStudioComponentIds" />`

OR
 
Reliable fix:
`FireGiant.HeatWave.DesignTime.targets` imports DTB targets form project system: 
https://github.com/dotnet/project-system/blob/5f3636c2064201fac04017900e0160193ee8627b/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L437

**Comment by vbaderks** [comment]
Note: on a clean machine (with no NuGet packaged installed) the Repro Steps requires an explicit msbuild -restore before executing msbuild -t:build -p:Configuration=Release -p:Platform=x64

**Comment by FireGiantHelp** [comment]
The Visual Studio team confirmed this issue is a breaking change in VS2022 17.13. We'll address the breaking change when one of our customers requires it.

Until then, you can work around the breaking change by adding the following line to the bottom of your .wixproj.

```xml
<Target Name="CollectSuggestedVisualStudioComponentIds" />
```

**Comment by jespersh** [comment]
Just to clarify @FireGiantHelp are we waiting for a new VS preview release?
I saw a report on this closed as External Other Product: https://developercommunity.visualstudio.com/t/VS-1713-Preview-2-breaks-WiX-v5-project/10809797

**Comment by FireGiantHelp** [comment]
@jespersh Visual Studio made it clear that this is an expected breaking change. We will need to update HeatWave to adapt to the breaking change.

None of our current customers are on Visual Studio preview builds, so supporting preview builds is not a priority for us. We will release an updated HeatWave to meet our customers' needs.

**Comment by CyberSinh** [comment]
Same issue on VS 2022 v17.13 RTM, released today.

**Comment by FireGiantHelp** [comment]
@CyberSinh You will need a version greater than HeatWave v1.0.4. Reach out to your FireGiant support contact to get early access.

**Comment by CyberSinh** [comment]
I'm not eligible for paid support. When will the HeatWave extension update be released to the general public?

**Comment by FireGiantHelp** [comment]
> I'm not eligible for paid support. 

Everyone is eligible for paid support. Sign up for [WiX Developer Direct](https://www.firegiant.com/wix-developer-direct/), and you'll get priority support like all our customers.

> When will the HeatWave extension update be released to the general public?

We do not have a date at this moment. We are actively working with our customers to ensure the next version of HeatWave meets their needs.

**Comment by aDisplayName** [comment]
Let us know who your customer is, and we will tell them the great benefit of upgrading to latest Visual Studio 17.13. :)

**Comment by tobyjohnm** [comment]
This is a problem for me. I updated Visual Studio yesterday and can't build installers without the workaround. I just warned the rest of the dev team to avoid updating VS. I'm surprised there isn't a greater sense of urgency here about getting a fix out. WIX v3 and v4 are now out of support. Meanwhile, the v5 that is supported is now broken and we're told there is no date in sight.

**Comment by aDisplayName** [comment]
> This is a problem for me. I updated Visual Studio yesterday and can't build installers without the workaround. I just warned the rest of the dev team to avoid updating VS. I'm surprised there isn't a greater sense of urgency here about getting a fix out. WIX v3 and v4 are now out of support. Meanwhile, the v5 that is supported is now broken and we're told there is no date in sight.

Another bug is related to the use of wixtoolset extension nuget packages. We decided to go forward with the VS upgrade, and use the dotnet CLI to perform the local build.  Our CI/CD pipeline is using dotnet CLI so it is not being affected.

**Comment by FireGiantHelp** [comment]
@tobyjohnm did you find that the one-line workaround did not work? We found that it was sufficient to address the breaking change in Visual Studio.

With an available workaround, the priority for a general fix was reduced, and we could focus on customer requirements for the next release of HeatWave.

**Comment by tobyjohnm** [comment]
The workaround does work, but we have more than 100 installers in our repo. I can't run a full build without touching all of them with something that only benefits me. I either have to hold those changes back, making my change management more difficult, or temporarily pollute all of them.

**Comment by elachlan** [comment]
Thank you for the work around!

**Comment by fforjanAVEVA** [comment]
@tobyjohnm  you shoudl consider the directory.build.props as it would apply to all your installer

**Comment by tobyjohnm** [comment]
@fforjanAVEVA can you provide a concrete example of how directory.build.props should be modified to add the necessary workaround line (CollectSuggestedVisualStudioComponentIds) to every WIX project file?

**Comment by fforjanAVEVA** [comment]
@tobyjohnm 
if you add the following as a Directory.build.targets file next to the solution - assuming the solution is at the root folder
```
<Project>
    <!-- https://github.com/firegiant/HeatWaveSupport/issues/73 -->
	<Target Condition="'$(MSBuildProjectExtension)'=='.wixproj'" Name="CollectSuggestedVisualStudioComponentIds" />
</Project>
```

then all the wixproj project shoudl automatically have the target being added.

**Comment by Patrick-3000** [comment]
Same issue here, even with 17.13.2.

**Comment by tompavaa** [comment]
Looks like this was fixed in 17.13.2 that was released on Feb 26:th.

**Comment by LtKlaus** [comment]
I updated my VS Pro to 17.13.2 this morning and it didn't fix this issue for me. Creating Directory.build.targets alongside my solution, as suggested above, did work.

**Comment by chrpai** [comment]
I just updated to 17.13.2 and I'm 100% broken.

**Comment by fforjanAVEVA** [comment]
@chrpai  did you try the workaround ?

**Comment by chrpai** [comment]
@fforjanAVEVA  I'm not interested in the workaround, I'm interested in the fix.  I have countless customers, repos, solutions, projects that are impacted by this.   Heatwave was released as a closed source "Free" "Community Edition" tool replacement of Votive which was a proper FOSS project.  Now it's being alluded that a fix is available but only if you pay for it.  Additionally there's talk of "maintainer fees" in the air.  I'm starting to feel like some really shady stuff is about to go down and I've been keeping quiet about it for far too long.

**Comment by chrpai** [comment]
I've rolled back to 17.12.4 and I'm just going to sit this one out and see how it plays out.

**Comment by trinare** [comment]
We are also having this problem. When is the planned release for the next version of HeatWave?

**Comment by FireGiantHelp** [comment]
We are very close to resolving the issue reported by a customer [as mentioned above](https://github.com/firegiant/HeatWaveSupport/issues/73#issuecomment-2655672947). We expect to release an update to HeatWave in the next week or two.

**Comment by petm2022** [comment]
I have the same issue with Visual Studio 17.12.3
- error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

**Comment by FireGiantHelp** [comment]
This should now be fixed in HeatWave v1.0.5 released today.

**Comment by fforjanAVEVA** [comment]
@FireGiantHelp  how does this get deploy to us ? I do not see any nuget package update ?

**Comment by maho123456emer** [comment]
In Visual Studio under "Extensions" -> "Manage Extensions..." you can find the tab "Installed". HeatWave should be listed there.

By the way: the new version works on my end. Thanks!

**Comment by fforjanAVEVA** [comment]
But the visual studio extensions should have no impact on command line build ?
(and my understand this issue was visible from command line, I may be wrong)
